// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7dLDQG6KQJ5S2DmQRfvHmlBJkchKLfSU',
    appId: '1:871138063486:web:845853c595a646db88542f',
    messagingSenderId: '871138063486',
    projectId: 'mainhealthapp-8c99b',
    authDomain: 'mainhealthapp-8c99b.firebaseapp.com',
    storageBucket: 'mainhealthapp-8c99b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcwRplf7tNYlR7xf6uOgi76o9YtVS9gos',
    appId: '1:871138063486:android:3351f16b79541e8888542f',
    messagingSenderId: '871138063486',
    projectId: 'mainhealthapp-8c99b',
    storageBucket: 'mainhealthapp-8c99b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk71QriDkXfcku-CBB0tZjUXHu4n3CLw4',
    appId: '1:871138063486:ios:0429c2f3c5a354cb88542f',
    messagingSenderId: '871138063486',
    projectId: 'mainhealthapp-8c99b',
    storageBucket: 'mainhealthapp-8c99b.firebasestorage.app',
    androidClientId: '871138063486-oi7hjjnrkh1uvruc32kh9d6gq4fi0spi.apps.googleusercontent.com',
    iosClientId: '871138063486-1guja9cjb7gbbtbb0j330n5epu9u46a2.apps.googleusercontent.com',
    iosBundleId: 'com.example.mentalHealth',
  );

}